name: Newman API Test

on:
  push:
    branches: ["main"]


jobs:
  run-api-tests:
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: installation de node jobs
        uses: actions/setup-node@v4

      - name: install libraries
        run: npm install

      - name: lancer le backend
        run: | 
          nohup node server.js > server.log 2>&1 &
          sleep 5


      - name: installation de Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: lancer newman
        run: |
          newman run "./postman/AtelierFinal.postman_collection.json" \
          -e "./postman/atelierFinal.postman_environment.json"